// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mve_exhaustive_search_cpp
Rcpp::List mve_exhaustive_search_cpp(const arma::vec& mu, const arma::mat& sigma, unsigned int k, double ridge_epsilon, bool enumerate_all, unsigned int max_samples, bool dedup_samples, bool compute_weights, bool normalize_weights, int normalization_type, bool do_checks);
RcppExport SEXP _SparsePortfolioSelection_mve_exhaustive_search_cpp(SEXP muSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP ridge_epsilonSEXP, SEXP enumerate_allSEXP, SEXP max_samplesSEXP, SEXP dedup_samplesSEXP, SEXP compute_weightsSEXP, SEXP normalize_weightsSEXP, SEXP normalization_typeSEXP, SEXP do_checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type enumerate_all(enumerate_allSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_samples(max_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type dedup_samples(dedup_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_weights(compute_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize_weights(normalize_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type normalization_type(normalization_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type do_checks(do_checksSEXP);
    rcpp_result_gen = Rcpp::wrap(mve_exhaustive_search_cpp(mu, sigma, k, ridge_epsilon, enumerate_all, max_samples, dedup_samples, compute_weights, normalize_weights, normalization_type, do_checks));
    return rcpp_result_gen;
END_RCPP
}
// mve_miqp_search_cpp
Rcpp::List mve_miqp_search_cpp(const arma::vec& mu, const arma::mat& sigma, unsigned int k, const arma::vec& fmin, const arma::vec& fmax, Rcpp::Nullable<arma::vec> x_start, Rcpp::Nullable<arma::uvec> v_start, int m, double gamma, bool exactly_k, unsigned int expand_rounds, double expand_factor, double expand_tol, double mipgap, double time_limit, int threads, double ridge_epsilon, bool normalize_weights, bool use_refit, bool verbose, bool do_checks);
RcppExport SEXP _SparsePortfolioSelection_mve_miqp_search_cpp(SEXP muSEXP, SEXP sigmaSEXP, SEXP kSEXP, SEXP fminSEXP, SEXP fmaxSEXP, SEXP x_startSEXP, SEXP v_startSEXP, SEXP mSEXP, SEXP gammaSEXP, SEXP exactly_kSEXP, SEXP expand_roundsSEXP, SEXP expand_factorSEXP, SEXP expand_tolSEXP, SEXP mipgapSEXP, SEXP time_limitSEXP, SEXP threadsSEXP, SEXP ridge_epsilonSEXP, SEXP normalize_weightsSEXP, SEXP use_refitSEXP, SEXP verboseSEXP, SEXP do_checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fmin(fminSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fmax(fmaxSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::vec> >::type x_start(x_startSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<arma::uvec> >::type v_start(v_startSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< bool >::type exactly_k(exactly_kSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type expand_rounds(expand_roundsSEXP);
    Rcpp::traits::input_parameter< double >::type expand_factor(expand_factorSEXP);
    Rcpp::traits::input_parameter< double >::type expand_tol(expand_tolSEXP);
    Rcpp::traits::input_parameter< double >::type mipgap(mipgapSEXP);
    Rcpp::traits::input_parameter< double >::type time_limit(time_limitSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize_weights(normalize_weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_refit(use_refitSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type do_checks(do_checksSEXP);
    rcpp_result_gen = Rcpp::wrap(mve_miqp_search_cpp(mu, sigma, k, fmin, fmax, x_start, v_start, m, gamma, exactly_k, expand_rounds, expand_factor, expand_tol, mipgap, time_limit, threads, ridge_epsilon, normalize_weights, use_refit, verbose, do_checks));
    return rcpp_result_gen;
END_RCPP
}
// compute_sr_cpp
double compute_sr_cpp(const arma::vec& weights, const arma::vec& mu, const arma::mat& sigma, const arma::uvec& selection, double ridge_epsilon, bool do_checks);
RcppExport SEXP _SparsePortfolioSelection_compute_sr_cpp(SEXP weightsSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP selectionSEXP, SEXP ridge_epsilonSEXP, SEXP do_checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type do_checks(do_checksSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_sr_cpp(weights, mu, sigma, selection, ridge_epsilon, do_checks));
    return rcpp_result_gen;
END_RCPP
}
// compute_mve_sr_cpp
double compute_mve_sr_cpp(const arma::vec& mu, const arma::mat& sigma, const arma::uvec& selection, double ridge_epsilon, bool do_checks);
RcppExport SEXP _SparsePortfolioSelection_compute_mve_sr_cpp(SEXP muSEXP, SEXP sigmaSEXP, SEXP selectionSEXP, SEXP ridge_epsilonSEXP, SEXP do_checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type do_checks(do_checksSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mve_sr_cpp(mu, sigma, selection, ridge_epsilon, do_checks));
    return rcpp_result_gen;
END_RCPP
}
// compute_mve_weights_cpp
arma::vec compute_mve_weights_cpp(const arma::vec& mu, const arma::mat& sigma, const arma::uvec& selection, double ridge_epsilon, bool normalize_weights, int normalization_type, bool do_checks);
RcppExport SEXP _SparsePortfolioSelection_compute_mve_weights_cpp(SEXP muSEXP, SEXP sigmaSEXP, SEXP selectionSEXP, SEXP ridge_epsilonSEXP, SEXP normalize_weightsSEXP, SEXP normalization_typeSEXP, SEXP do_checksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type selection(selectionSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize_weights(normalize_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type normalization_type(normalization_typeSEXP);
    Rcpp::traits::input_parameter< bool >::type do_checks(do_checksSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_mve_weights_cpp(mu, sigma, selection, ridge_epsilon, normalize_weights, normalization_type, do_checks));
    return rcpp_result_gen;
END_RCPP
}
// stabilize_sigma_cpp
arma::mat stabilize_sigma_cpp(const arma::mat& sigma, double ridge_epsilon);
RcppExport SEXP _SparsePortfolioSelection_stabilize_sigma_cpp(SEXP sigmaSEXP, SEXP ridge_epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(stabilize_sigma_cpp(sigma, ridge_epsilon));
    return rcpp_result_gen;
END_RCPP
}
// normalize_weights_cpp
arma::vec normalize_weights_cpp(const arma::vec& w, double epsilon, int type);
RcppExport SEXP _SparsePortfolioSelection_normalize_weights_cpp(SEXP wSEXP, SEXP epsilonSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< int >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_weights_cpp(w, epsilon, type));
    return rcpp_result_gen;
END_RCPP
}
// safe_chol_cpp
arma::mat safe_chol_cpp(const arma::mat& Q, double ridge_epsilon);
RcppExport SEXP _SparsePortfolioSelection_safe_chol_cpp(SEXP QSEXP, SEXP ridge_epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(safe_chol_cpp(Q, ridge_epsilon));
    return rcpp_result_gen;
END_RCPP
}
// design_from_moments_cpp
Rcpp::List design_from_moments_cpp(const arma::vec& mu, const arma::mat& sigma, double n_obs, double ridge_epsilon);
RcppExport SEXP _SparsePortfolioSelection_design_from_moments_cpp(SEXP muSEXP, SEXP sigmaSEXP, SEXP n_obsSEXP, SEXP ridge_epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< double >::type ridge_epsilon(ridge_epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(design_from_moments_cpp(mu, sigma, n_obs, ridge_epsilon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SparsePortfolioSelection_mve_exhaustive_search_cpp", (DL_FUNC) &_SparsePortfolioSelection_mve_exhaustive_search_cpp, 11},
    {"_SparsePortfolioSelection_mve_miqp_search_cpp", (DL_FUNC) &_SparsePortfolioSelection_mve_miqp_search_cpp, 21},
    {"_SparsePortfolioSelection_compute_sr_cpp", (DL_FUNC) &_SparsePortfolioSelection_compute_sr_cpp, 6},
    {"_SparsePortfolioSelection_compute_mve_sr_cpp", (DL_FUNC) &_SparsePortfolioSelection_compute_mve_sr_cpp, 5},
    {"_SparsePortfolioSelection_compute_mve_weights_cpp", (DL_FUNC) &_SparsePortfolioSelection_compute_mve_weights_cpp, 7},
    {"_SparsePortfolioSelection_stabilize_sigma_cpp", (DL_FUNC) &_SparsePortfolioSelection_stabilize_sigma_cpp, 2},
    {"_SparsePortfolioSelection_normalize_weights_cpp", (DL_FUNC) &_SparsePortfolioSelection_normalize_weights_cpp, 3},
    {"_SparsePortfolioSelection_safe_chol_cpp", (DL_FUNC) &_SparsePortfolioSelection_safe_chol_cpp, 2},
    {"_SparsePortfolioSelection_design_from_moments_cpp", (DL_FUNC) &_SparsePortfolioSelection_design_from_moments_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SparsePortfolioSelection(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
