# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Portfolio Sharpe Ratio
#'
#' Given a vector of portfolio weights, a vector of mean returns, and a covariance matrix,
#' this function computes the Sharpe ratio defined as
#' \deqn{\frac{w^T \mu}{\sqrt{w^T \Sigma w}}.}
#'
#' @param weights A numeric vector of portfolio weights.
#' @param mu A numeric vector of expected returns.
#' @param sigma A numeric covariance matrix.
#' @param do_checks Logical flag indicating whether to perform input checks (default = false).
#' @return A double representing the Sharpe ratio.
compute_sr_cpp <- function(weights, mu, sigma, do_checks = FALSE) {
    .Call(`_SparsePortfolioSelection_compute_sr_cpp`, weights, mu, sigma, do_checks)
}

#' Compute Mean-Variance Efficient Portfolio Sharpe Ratio
#'
#' Given a mean vector \eqn{\mu}, a covariance matrix \eqn{\Sigma},
#' and an asset selection vector, this function computes the optimal Sharpe ratio defined as
#' \deqn{\sqrt{\mu^T \Sigma^{-1}\mu}}
#' over the selected assets.
#' If the provided asset selection vector has length less than N,
#' the function uses the subset of assets and computes the ratio using those assets.
#'
#' @param mu Mean vector.
#' @param sigma Covariance matrix.
#' @param selection Index vector with asset indices. Default is an empty
#'        vector, which means all assets are selected.
#' @param do_checks Logical flag indicating whether to perform input checks (default = FALSE).
#' @return A scalar value corresponding to \eqn{\sqrt{\mu^T \Sigma^{-1}\mu}}.
compute_mve_sr_cpp <- function(mu, sigma, selection, do_checks = FALSE) {
    .Call(`_SparsePortfolioSelection_compute_mve_sr_cpp`, mu, sigma, selection, do_checks)
}

#' Compute Mean-Variance Efficient (MVE) Portfolio Weights
#'
#' Given a risk-aversion parameter \eqn{\gamma}, a first moment vector, a second moment matrix,
#' and a selection index vector, this function computes the mean variance efficient portfolio weights
#' \deqn{w = \frac{1}{\gamma}\, \text{second\_moment}^{-1}\, \text{first\_moment}},
#' over the selected assets.
#' If the provided asset selection vector has length less than N,
#' the function returns an N-length weight vector with zeros for the unselected assets.
#'
#' @param mu First moment vector.
#' @param second_moment Second moment matrix.
#' @param selection Unsigned integer vector with asset indices. Default is an empty
#'        vector, which means all assets are selected.
#' @param gamma Risk aversion parameter. Default is 1.
#' @param do_checks Logical flag indicating whether to perform input checks (default = FALSE).
#' @return An N-length vector of mean variance efficient weights.
compute_mve_weights_cpp <- function(mu, second_moment, selection, gamma = 1.0, do_checks = FALSE) {
    .Call(`_SparsePortfolioSelection_compute_mve_weights_cpp`, mu, second_moment, selection, gamma, do_checks)
}

#' Compute Mean-Variance Efficient Sharpe Ratio with Cardinality K
#'
#' This function takes as inputs the mean vector \code{mu}, the covariance matrix \code{sigma},
#' the maximum active portfolio cardinality \code{max_card},
#' and the maximum number of combinations per cardinality to evaluate \code{max_comb}.
#' With these inputs, it searches over all combinations of assets with cardinality from 1 up to \code{max_card}
#' and computes the Sharpe ratio defined as
#' \eqn{\mu^T \, \sigma^{-1}\, \mu}.
#' It returns the highest Sharpe ratio found along with the associated asset selection.
#'
#' @param mu Mean vector.
#' @param sigma Coveriance matrix.
#' @param max_card Maximum investment cardinality (from 1 up to the number of assets).
#' @param max_comb Maximum number of combinations to consider. If 0 (default),
#'                 all combinations are computed.
#' @param do_checks Logical flag indicating whether to perform input checks (default = \code{FALSE}).
#' @return A list with \code{sr} (the optimal Sharpe ratio) and \code{selection} (the asset indices of the optimal selection).
compute_mve_sr_cardk_cpp <- function(mu, sigma, max_card, max_comb = 0L, do_checks = FALSE) {
    .Call(`_SparsePortfolioSelection_compute_mve_sr_cardk_cpp`, mu, sigma, max_card, max_comb, do_checks)
}

#' Simulate Sharpe Ratio Loss
#'
#' This function simulates a sample of size \code{n_obs} from a multivariate normal
#' distribution with mean vector \code{mu} and covariance matrix \code{sigma}.
#' It computes the sample mean vector (\code{mu_sample}) and the sample covariance matrix (\code{sigma_sample}),
#' then calls \code{compute_sr_sparsity_loss} with the population and sample parameters,
#' the maximum cardinality (\code{max_card}), and the maximum number of combinations (\code{max_comb}).
#'
#' @param mu A numeric vector; the population mean vector.
#' @param sigma A numeric matrix; the population covariance matrix.
#' @param n_obs An integer specifying the sample size to simulate.
#' @param max_card Maximum cardinality to consider (from 1 up to the number of assets).
#' @param max_comb Maximum number of combinations to consider. If 0 (default),
#'                 all combinations are computed.
#' @param do_checks Logical; if TRUE, input checks are performed.
#'
#' @return // @return A list with:
#'    - \code{sample_mve_sr} computed as the optimal sample mve Sharpe ratio,
#'    - \code{sample_mve_sr_cardk} computed as the optimal sample mve Sharpe ratio
#'      with cardinality \code{max_card},
#'    - \code{mve_sr_cardk_est_term} computed as \eqn{w^T \mu^T / \sqrt{w^T\sigma w}}
#'      where \code{w} are the optimal sample mve weights,
#'    - \code{mve_sr_cardk_sel_term} computed as \eqn{\mu_S^T  \sigma_S^{-1} \mu_S}
#'      where \code{S} is the set of assets yielding the optimal sample mve Sharpe ratio.
simulate_mve_sr_cpp <- function(mu, sigma, n_obs, max_card, max_comb = 0L, do_checks = FALSE) {
    .Call(`_SparsePortfolioSelection_simulate_mve_sr_cpp`, mu, sigma, n_obs, max_card, max_comb, do_checks)
}

