# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mve_exhaustive_search_cpp <- function(mu, sigma, k, epsilon, stabilize_sigma, do_checks, enumerate_all, max_samples, dedup_samples, compute_weights) {
    .Call(`_SparsePortfolioSelection_mve_exhaustive_search_cpp`, mu, sigma, k, epsilon, stabilize_sigma, do_checks, enumerate_all, max_samples, dedup_samples, compute_weights)
}

mve_miqp_search_cpp <- function(mu, sigma, k, exactly_k, m, gamma, fmin, fmax, expand_rounds, expand_factor, expand_tol, mipgap, time_limit, threads, x_start, v_start, compute_weights, normalize_wts, use_refit, verbose, epsilon, stabilize_sigma, do_checks) {
    .Call(`_SparsePortfolioSelection_mve_miqp_search_cpp`, mu, sigma, k, exactly_k, m, gamma, fmin, fmax, expand_rounds, expand_factor, expand_tol, mipgap, time_limit, threads, x_start, v_start, compute_weights, normalize_wts, use_refit, verbose, epsilon, stabilize_sigma, do_checks)
}

compute_sr_cpp <- function(weights, mu, sigma, selection, epsilon, stabilize_sigma, do_checks) {
    .Call(`_SparsePortfolioSelection_compute_sr_cpp`, weights, mu, sigma, selection, epsilon, stabilize_sigma, do_checks)
}

compute_mve_sr_cpp <- function(mu, sigma, selection, epsilon, stabilize_sigma, do_checks) {
    .Call(`_SparsePortfolioSelection_compute_mve_sr_cpp`, mu, sigma, selection, epsilon, stabilize_sigma, do_checks)
}

compute_mve_weights_cpp <- function(mu, sigma, selection, normalize_w, epsilon, stabilize_sigma, do_checks) {
    .Call(`_SparsePortfolioSelection_compute_mve_weights_cpp`, mu, sigma, selection, normalize_w, epsilon, stabilize_sigma, do_checks)
}

prep_covariance_cpp <- function(sigma, epsilon, stabilize) {
    .Call(`_SparsePortfolioSelection_prep_covariance_cpp`, sigma, epsilon, stabilize)
}

normalize_weights_cpp <- function(w, mode, tol, do_checks) {
    .Call(`_SparsePortfolioSelection_normalize_weights_cpp`, w, mode, tol, do_checks)
}

eps_ridge_cpp <- function() {
    .Call(`_SparsePortfolioSelection_eps_ridge_cpp`)
}

safe_chol_cpp <- function(Q, base_bump, max_tries) {
    .Call(`_SparsePortfolioSelection_safe_chol_cpp`, Q, base_bump, max_tries)
}

design_from_moments_cpp <- function(mu, sigma, n_obs, epsilon, stabilize_sigma) {
    .Call(`_SparsePortfolioSelection_design_from_moments_cpp`, mu, sigma, n_obs, epsilon, stabilize_sigma)
}

